### ISSUE TITLE
feat: Adding `DEV`, `PROD`, `TEST` environment variables

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/foca#247]
I would like to be able to change the code of my application using env variables, eg change the port based on which mode the FOCA app is running or change the configuration etc. This might seem like a per project level requirement, but having this defined either in config.yaml with strict typing to standardize the variable name might be helpful. 

For example being able to do something like:

```python
# Development: Permissive CORS
if app.mode == APIMode.DEV:
    CORS(app, origins="*")

# Production: Strict CORS
if app.mode == APIMode.PROD:
    CORS(app, origins=["https://myapp.com"])
```

Maybe extra configs for those modes in config.yaml, with which we can overwrite some config fields. 

```yaml
environments:
  dev:
    server:
      debug: True
      port: 8080
      use_reloader: True
    
    db:
      host: localhost
      port: 27017

  prod:
    server:
      debug: False
      port: 80
      use_reloader: False
    
    log:
      root:
        level: 20
      handlers:
        console:
          level: 20

  staging:
    server:
      debug: False
      port: 8080
```
