### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#54]
- [ ] mention all features
  - Connexion factory
  - CORS support
  - OpenAPI 2.x/3.x spec regsitration
  - Endpoint protection / JWT validation
  - Database (MongoDB)
  - Background tasks (RabbitMQ & Celery)
- [ ] describe usage of main FOCA class
- [ ] link to exampe app (#50)
- [ ] add some ELIXIR Cloud & AAI branding, contacts etc.

**Comment by uniqueg** [comment]
Something that @stikos wrote previously which may be of use (although probably somewhat outdated and not detailed enough):

```
config: A Dict object, parsed from a proper YAML configuration file,
               containing the required FOCA-specific configuration parameters
               (under the reserved `foca` key), along with any
               serivce-specific parameters. It should follow the format shown
               below:
               {
                   foca:
                       db:
                           # Any database parameters
                       api:
                           # Any OpenAPI specifications
                       errors:
                           # Any custom errors
                       celery:
                           # Any Celery parameters for background jobs
                       log:
                           # Any log parameters
                       security:
                           # Any protected endpoints/security parameters
                       server:
                           # Any general Flask/Connexion/Gunicorn parameters
                           # (e.g., host, port...)
                   # Any parameter below this point is service-specifc and
                   will be added to `app.config` without validation
                   service_specific_section_1:
                       param_1: my_param_1
                       param_2: my_param_2
                   service_specific_section_2:
                       param_1: my_param_1
                       param_2: my_param_2
               }
```
